setting:
    checkRate: 30
    sendGIF: false
    imagesCache: logs/weibo
    remote: false

websocket:
    url: wss://cdn.amiyabot.com/api/v1/weibo/ws
    token: ''
    reconnectAttempts: 5
    reconnectDelay: 5

sendInterval: 0.2
sendAsync: false

listen:
    -   uid: '6279793937'
        name: '明日方舟'
    -   uid: '6441489862'
        name: '明日方舟朝陇山'
    -   uid: '7745672941'
        name: '明日方舟终末地'
    -   uid: '7697896274'
        name: '来自星尘'
    -   uid: '7499841383'
        name: '泰拉记事社'
    -   uid: '7840846173'
        name: '泡姆泡姆'

block: [ ]
